/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    Star_Destroyer: THREE.Mesh;
  };
  materials: {
    ['Light grey']: THREE.MeshStandardMaterial;
  };
};

export function Destroyer(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    'assets/Star destroyer-transformed.glb'
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-19.2, 0, 0]} rotation={[0, 1.57, 0]}>
        <pointLight
          intensity={50}
          decay={2}
          distance={1.9}
          color="#648aff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-21.73, 0, 0]} rotation={[0, 1.57, 0]}>
        <pointLight
          intensity={100}
          decay={2}
          distance={3.5}
          color="#1e5bff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-19.2, 0, -7.59]} rotation={[0, 1.57, 0]}>
        <pointLight
          intensity={50}
          decay={2}
          distance={1.6}
          color="#648aff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-20.85, 0, -7.59]} rotation={[0, 1.57, 0]}>
        <pointLight
          intensity={100}
          decay={2}
          distance={2.5}
          color="#1e5bff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-19.2, 0, 7.51]} rotation={[0, 1.57, 0]}>
        <pointLight
          intensity={50}
          decay={2}
          distance={1.6}
          color="#648aff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-20.85, 0, 7.51]} rotation={[0, 1.57, 0]}>
        <pointLight
          intensity={100}
          decay={2}
          distance={2.5}
          color="#1e5bff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Star_Destroyer.geometry}
        material={materials['Light grey']}
      />
    </group>
  );
}

useGLTF.preload('assets/Star destroyer-transformed.glb');
